name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every sunday
    - cron: "0 12 * * 0"

jobs:
  update-readme:
    name: Update readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Updated readme graph with new metrics
          SHOW_TITLE: false
          BLOCKS: -#
          TIME_RANGE: last_year
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
